version: '2'
services:
    dev_server:
        image: node:10.16.3
        command: npm run start:dev
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - '8080:8080'

    server_watcher:
        image: node:10.16.3
        command: npm run watch:server
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
